app/models/navigation.py
from typing import TYPE_CHECKING

from flask import has_request_context, url_for
from sqlalchemy import Boolean, Column, Integer, String
from sqlalchemy.orm import relationship
from sqlalchemy.schema import ForeignKey

from app import get_locale
from app.extensions import mapper_registry
from app.models.activity import Activity
from app.models.base_model import BaseEntity

if TYPE_CHECKING:
    from app.models.page import Page


@mapper_registry.mapped
class NavigationEntry(BaseEntity):
    __tablename__ = "navigation_entry"
    prints = ("id", "parent_id", "nl_title", "en_title", "url", "external")

    parent_id = Column(Integer, ForeignKey("navigation_entry.id"))
    page_id = Column(Integer, ForeignKey("page.id"))
    nl_title = Column(String(256))
    en_title = Column(String(256))
    url = Column(String(256))
    external = Column(Boolean)
    activity_list = Column(Boolean)
    position: int = Column(Integer, nullable=False)
    order_children_alphabetically = Column(Boolean(), default=False, nullable=False)

    # Both parent and children have explicit raiseload to prevent unwanted
    # explosion of queries. Please see navigation_repo for respective loaders.
    parent: "NavigationEntry" = relationship(
        "NavigationEntry",
        remote_side="NavigationEntry.id",
        back_populates="children",
        lazy="raise",
    )

    children: list["NavigationEntry"] = relationship(
        "NavigationEntry",
        remote_side="NavigationEntry.parent_id",
        order_by="NavigationEntry.position",
        back_populates="parent",
        lazy="raise",
    )

    page: "Page" = relationship(
        "Page", lazy="joined", back_populates="navigation_entries"
    )

    @property
    def title(self) -> str:
        locale = "en"
        if has_request_context():
            locale = get_locale()
        if locale == "nl" and self.nl_title:
            return self.nl_title
        elif locale == "en" and self.en_title:
            return self.en_title
        elif self.nl_title:
            return self.nl_title
        elif self.en_title:
            return self.en_title
        return "N/A"

    @property
    def href(self):
        if self.activity_list:
            return url_for("activity.view")
        elif self.page:
            return f"/{self.page.path}"
        elif self.external and self.url:
            return "https://" + self.url
        else:
            return f"/{self.url}"

    @property
    def activities(self) -> list[Activity]:
        from app.service import activity_service

        if not self.activity_list:
            raise NotImplementedError()
        else:
            return activity_service.get_activities_ending_after_now()

app/views/home.py
import json
import random
import re
from datetime import date
from typing import Literal

from flask import Blueprint, make_response, redirect, render_template
from flask_login import current_user
from sqlalchemy import desc

from app import app, db
from app.models.news import News
from app.service import activity_service, company_service, privacy_service
from app.views.viewmodel.activity import ActivityViewModel
from app.views.viewmodel.jobs import JobsViewModel
from app.views.viewmodel.news import NewsViewModel

blueprint = Blueprint("home", __name__)


@blueprint.route("/", methods=["GET"])
def home():
    jobs = company_service.find_all_jobs(filter_inactive=True)
    r = random.Random(str(date.today()))
    indices = [i for i in range(len(jobs))]
    r.shuffle(indices)
    jobs_view_models = [JobsViewModel(jobs[i]) for i in indices[:4]]

    activities = activity_service.get_activities_ending_after_now()

    activity_view_models = [ActivityViewModel(a, current_user) for a in activities[:4]]

    news: list[News] = (
        db.session.query(News)
        .filter(
            News.publish_date <= date.today(),
            db.or_(current_user.has_paid, db.not_(News.needs_paid)),
        )
        .order_by(desc(News.publish_date), desc(News.id))
        .limit(8)
        .all()
    )

    news_view_models = [NewsViewModel(n) for n in news]

    return render_template(
        "home/home.htm",
        activities=activity_view_models,
        title="Homepage",
        news=news_view_models,
        jobs=jobs_view_models,
    )


@blueprint.route("/privacy/policy/<any(nl,en):lang>/")
def privacy_policy(lang: Literal["en", "nl"]):
    policies = privacy_service.find_policies()
    if lang == "en":
        return redirect(policies.url_en)
    if lang == "nl":
        return redirect(policies.url_nl)


rule_parser = re.compile(r"<(.+?)>")
splitter = re.compile(r"<.+?>")


@blueprint.route("/jsglue.js")
def serve_js():
    """
    Based on https://github.com/stewartpark/Flask-JSGlue.

    The code is inlined, because the pypi is not up-to-date and using the git version
    results in unknown template directories. This may be fixed after a new version
    is published and installable to site-package.
    """
    output = []
    for r in app.url_map.iter_rules():
        endpoint = r.endpoint
        if app.config["APPLICATION_ROOT"] == "/" or not app.config["APPLICATION_ROOT"]:
            rule = r.rule
        else:
            rule = "{root}{rule}".format(
                root=app.config["APPLICATION_ROOT"], rule=r.rule
            )
        rule_args = [x.split(":")[-1] for x in rule_parser.findall(rule)]
        rule_tr = splitter.split(rule)
        output.append((endpoint, rule_tr, rule_args))

    rules = sorted(output, key=lambda x: len(x[1]), reverse=True)

    return make_response(
        render_template("js_bridge.js", namespace="Flask", rules=json.dumps(rules)),
        200,
        {"Content-Type": "text/javascript"},
    )

app/views/lang.py
#!/usr/bin/env python

from flask import Blueprint, flash, redirect, session, url_for
from flask_babel import _, refresh
from flask_login import current_user

from app import constants, db
from app.views import get_safe_redirect_url

blueprint = Blueprint("lang", __name__, url_prefix="/lang")


@blueprint.route("/set/<path:lang>/", methods=["GET"])
def set_user_lang(lang=None):
    if lang not in constants.LANGUAGES.keys():
        flash(_("Language unsupported on this site") + ": " + lang, "warning")
        return redirect(get_safe_redirect_url())
    if current_user.is_anonymous:
        flash(_("You need to be logged in to set a permanent language."))
        return redirect(get_safe_redirect_url())

    current_user.locale = lang
    if "lang" in session:
        del session["lang"]
    db.session.add(current_user)
    db.session.commit()
    refresh()
    return redirect(get_safe_redirect_url())


@blueprint.route("/<path:lang>/", methods=["GET"])
def set_lang(lang=None):
    if lang not in constants.LANGUAGES.keys():
        flash(_("Language unsupported on this site") + ": " + lang, "warning")
        return redirect(get_safe_redirect_url())

    session["lang"] = lang

    # Show option to make language setting permanent if the user is logged in,
    # and the new language is not the user's default langauge.
    if current_user.is_authenticated and current_user.locale != lang:
        msg = _(
            "{} is now set as language for this session. To make this "
            "setting permanent, <a href='{}'>click here</a>"
        )
        flash(
            msg.format(
                constants.LANGUAGES[lang], url_for("lang.set_user_lang", lang=lang)
            ),
            "safe",
        )
    return redirect(get_safe_redirect_url())

app/views/navigation.py
from flask import Blueprint, render_template
from flask_babel import _

from app.decorators import require_role
from app.roles import Roles

blueprint = Blueprint("navigation", __name__, url_prefix="/navigation")


@blueprint.route("/")
@require_role(Roles.NAVIGATION_WRITE)
def view():
    return render_template("vue_content.htm", title=_("Navigation"))


@blueprint.route("/create/", methods=["GET"])
@blueprint.route("/<navigation_entry:entry>/edit/", methods=["GET"])
@require_role(Roles.NAVIGATION_WRITE)
def edit(entry=None):
    if entry:
        title = _("Edit navigation entry")
    else:
        title = _("Create navigation entry")
    return render_template("vue_content.htm", title=title)

app/views/saml.py
from flask import Blueprint, flash, redirect, url_for
from flask_babel import _
from flask_login import current_user, login_required

from app.decorators import require_role, response_headers
from app.exceptions.base import ValidationException
from app.models.user import User
from app.roles import Roles
from app.service import saml_service
from app.views import get_safe_redirect_url, set_redirect_location_if_not_set

blueprint = Blueprint("saml", __name__, url_prefix="/saml")
saml_info = None


@blueprint.before_request
def build_saml_info():
    global saml_info
    saml_info = saml_service.build_saml_info()


@blueprint.route("/sign-in/", methods=["GET"])
def login():
    """Initiate a login with SURFconext."""

    if current_user.is_authenticated:
        return redirect(get_safe_redirect_url())

    set_redirect_location_if_not_set()

    return redirect(
        saml_service.initiate_login(saml_info, url_for("login.sign_in_saml_response"))
    )


@blueprint.route("/sign-up/", methods=["GET"])
def sign_up():
    """
    Initiate a sign-up session with SURFconext.

    Initiate a sign-up session by first letting the user log in via SURFconext
    to partially pre-fill the sign-up form.
    """

    if current_user.is_authenticated:
        return redirect(get_safe_redirect_url())

    return redirect(
        saml_service.initiate_login(
            saml_info, url_for("signup.sign_up_saml_response"), force_authn=True
        )
    )


@blueprint.route("/link-account/", methods=["GET"])
@login_required
def link_account():
    """
    Let a user link his/her account.

    Let the currently logged in user log in in SURFconext to
    link his/her via account to his UvA account.
    """
    set_redirect_location_if_not_set()

    if current_user.student_id_confirmed:
        flash(_("Your account is already linked to a UvA account."), "danger")
        return redirect(get_safe_redirect_url())

    return redirect(
        saml_service.initiate_login(
            saml_info,
            url_for("signup.process_account_linking_saml_response"),
            force_authn=True,
        )
    )


@blueprint.route("/link-account/<user:user>/", methods=["GET"])
@login_required
@require_role(Roles.USER_WRITE)
def link_other_account(user: User):
    """
    Link the account of another user.

    Let a user log in via SURFconext to link that UvA account to the via
    account with id user_id.
    """
    set_redirect_location_if_not_set()

    saml_service.set_linking_user(user)

    return redirect(
        saml_service.initiate_login(
            saml_info,
            url_for("signup.process_account_linking_saml_response"),
            force_authn=True,
        )
    )


@blueprint.route("/acs/", methods=["POST"])
def assertion_consumer_service():
    """
    The Assertion Consumer Service endpoint for SAML IDP responses.

    This endpoint receives and processes the SAML response from SURFconext
    and then redirects to the handler set by initiate_login
    (which saves it in the RelayState parameter of the SAML request).
    """

    try:
        saml_service.process_response(saml_info)
    except ValidationException:
        flash(_("The response from SURFconext was invalid."), "danger")

        return redirect(get_safe_redirect_url())

    redirect_url = saml_service.get_relaystate_redirect_url(
        saml_info, url_for("home.home")
    )

    return redirect(redirect_url)


@blueprint.route("/metadata/", methods=["GET"])
@response_headers(
    {
        "Content-Type": "application/xml",
        "Content-Disposition": 'inline; filename="metadata.xml"',
    }
)
def metadata():
    """Build the metadata XML and output it."""

    return saml_service.build_metadata(saml_info)

app/views/vue.py
from flask import Blueprint, redirect, render_template
from flask_babel import get_locale
from flask_babel import gettext as _
from flask_login import login_required

from app.decorators import require_favourer_or_membership, require_role
from app.models.committee import Committee
from app.roles import Roles
from app.service import company_service
from app.views.file import send_picture

blueprint = Blueprint("vue", __name__)


@blueprint.route("/bug/report/")
@login_required
def bug_report():
    return public(title=_("Report a bug"))


@blueprint.route("/ereleden/", methods=["GET"])
@blueprint.route("/members-of-merit/", methods=["GET"])
def members_of_merit():
    return public(_("Members of merit"))


@blueprint.route("/jobs/", methods=["GET"])
def jobs():
    return public(_("Jobs"), "company-job-overview")


@blueprint.route("/companies/", methods=["GET"])
def companies():
    """Handle all public vue routes, defined in frontend/index.ts."""
    return public(_("Companies"), "company-overview")


@blueprint.route("/search/", methods=["GET"])
def search():
    return public(_("Search"), "search-index")


def public(title, keep_alive_include=None):
    """Handle all public vue routes, defined in frontend/index.ts."""
    return render_template(
        "vue_content.htm", keep_alive_include=keep_alive_include, title=title
    )


@blueprint.route("/photos/", methods=["GET"], defaults=dict(title=_("Photos")))
@blueprint.route("/photos/<path:_>", methods=["GET"], defaults=dict(title=_("Photos")))
@require_favourer_or_membership
def membership(title, _=""):
    """Handle all member-only vue routes, defined in frontend/index.ts."""
    return render_template("vue_content.htm", title=title)


@blueprint.route("/jobs/<int:job_id>/", methods=["GET"])
def view(job_id):
    """Handle all company resource vue route, defined in frontend/index.ts."""
    job = company_service.get_job_by_id(job_id)
    title = job.title_en if get_locale() == "en" else job.title_nl
    return render_template(
        "vue_content.htm", keep_alive_include="company-overview", title=title
    )


@blueprint.route("/lectures/", methods=["GET"])
def mailinglist_lecture_subscribe():
    return render_template("vue_content.htm", title=_("Lectures"))


@blueprint.route("/mailinglists/", methods=["GET"])
@blueprint.route("/mailinglists/<path:__>", methods=["GET"])
@require_role(Roles.MAILINGLIST_ADMIN)
def mailinglists(__=""):
    return render_template(
        "vue_content.htm",
        title=_("Mailinglists"),
        keep_alive_include="mailinglists-overview",
    )


@blueprint.route("/commissie/", methods=["GET"])
def committees():
    return render_template(
        "vue_content.htm",
        title=_("Committees"),
        keep_alive_include="committee-overview",
    )


@blueprint.route("/committee/picture/<committee:committee>/")
@blueprint.route("/committee/picture/<committee:committee>/<picture_type>/")
def committee_picture(committee: Committee, picture_type=None):
    if committee.picture_file_id is None:
        return redirect("/static/img/via_committee_default.jpg")

    return send_picture(
        committee.picture_file_id,
        f"committee_picture_{committee.en_name}",
        picture_type,
        thumbnail_size=(800, 600),
    )


@blueprint.route("/committee/create/", methods=["GET"])
@blueprint.route("/committee/<committee:committee>/edit/", methods=["GET"])
@require_role(Roles.GROUP_WRITE)
def committee_edit(committee=None):
    if committee:
        title = _("Edit committee")
    else:
        title = _("Create committee")
    return render_template(
        "vue_content.htm", title=title, keep_alive_include="committee-overview"
    )

app/templates/navigation/language_dropdown.htm
<ul class="nav nav-language">
    <li class="nav-item">
        <a class="nav-link {% if get_locale() == 'nl' %}  active  {% endif %}"
            href="{{url_for('lang.set_lang', lang='nl')}}">Nederlands</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if get_locale() == 'en' %}  active  {% endif %}"
            href="{{url_for('lang.set_lang', lang='en')}}">English</a>
    </li>
</ul>

app/templates/navigation/sidenav.htm
<ul class="nav nav-stacked nav-tabs">
	{% if current_page.count('/') > 0 %}
	<li>
		<a href="{{ url_for('page.view_page', page_path='/'.join(current_page.split('/')[:-1])) }}"><i class="fas fa-chevron-left"></i> Go back</a>
	{% endif %}

	{% for sibbling in sibblings %}
		{% if sibbling.path == current_page %}
			<li class="active">
				<a href="">{{sibbling.title}}</a>
			</li>

			{% for child in children %}
				<li>
				<a href="{{ url_for('page.view_page', page_path=child.path) }}"><i class="fas fa-chevron-right"></i> {{child.title}}</a>
				</li>
			{% endfor %}
		{% else %}
			<li>
				<a href="{{ url_for('page.view_page', page_path=sibbling.path) }}">{{sibbling.title}}</a>
			</li>
		{% endif %}

	{% endfor %}
</ul>

app/templates/navigation/user_dropdown.htm
{% if current_user.is_anonymous %}

    {{ render_uvanetid_signin_button(_('Log in with UvAnetID'), href=url_for('saml.login'), small=True) }}
    <hr class="hr-small">

    <form method="post" name="sign-in" id="sign-in-menu"
          action="{{ url_for('login.sign_in') }}">
        {{ login_form.csrf_token }}
        {{ render_field(login_form.email) }}
        {{ render_field(login_form.password) }}

        {{ render_submit('Log in') }}
        <ul class='list-unstyled' id='dropmenu-list'>
            <li>
                <a href="{{ url_for('signup.sign_up') }}">{{ _('Register') }}</a>
            </li>
            <li>
                <a href="{{ url_for('signup.request_password') }}">{{ _('Forgot password?') }}</a>
            </li>
        </ul>
    </form>
{% else %}
    <img src="{{ navigation_view.avatar }}" alt="User avatar"
         class="user-image img-rounded d-none d-sm-block">
    <div class="user-information">
        <h4 class="username">{{ navigation_view.name }}</h4>
        <p>{{ navigation_view.email }}</p>
        <p>
            <i class="fas fa-user"></i>
            <a href="{{ url_for('user.view_single_user', user=current_user) }}">{{ _("Show profile") }}</a>
        </p>
        {% if navigation_view.show_admin_link %}
            <p>
                <i class="fas fa-cogs"></i>
                <a href="{{ url_for('admin.view') }}">{{ _('Admin') }}</a>
            </p>
        {% endif %}
    </div>
    <div class="logout-container">
        <a href="{{ url_for('login.sign_out') }}">
            <button class="btn btn-primary fullWidth">{{ _("Log off") }}</button>
        </a>
    </div>
{% endif %}

app/templates/navigation/view_backtrack.htm
<a-breadcrumb v-cloak="">
    <a-breadcrumb-item>
        <a href="{{ url_for("home.home") }}">{{ _('Home') }}</a>
    </a-breadcrumb-item>
    {% for tracker in backtrack %}
        <a-breadcrumb-item>
            <a href="{{ tracker.href }}">{{ tracker.title }}</a>
        </a-breadcrumb-item>
    {% endfor %}
</a-breadcrumb>

app/templates/navigation/view_bar.htm
{% from "macros/form.htm" import render_field, render_checkbox, render_submit %}
{% from "user/macros/uvanetid.htm" import render_uvanetid_signin_button %}
    <nav class="navbar navbar-expand-md navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header d-flex">

                <!-- The mobile nav toggle -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse"  aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- The (svg) logo -->
                <a class="navbar-brand" href="/"><img src="{{ navigation_view.icon_uri }}" width="110"/></a>

                <!-- Dropdowns buttons for small menu -->
                <div class="navbar-right">
                    <a class="btn btn-link text-decoration-none" href="{{ url_for('vue.search') }}">
                        <i class="d-block d-md-none fas fa-large fa-search"></i>
                    </a>
                    <button class="btn btn-link text-decoration-none" data-target="#navbar-collapse-1" data-toggle="collapse">
                        <i class="d-block d-md-none fas fa-large fa-globe-europe"></i>
                    </button>
                    <button class="btn btn-link" data-target="#navbar-collapse-2" data-toggle="collapse">
                        {% if current_user.is_anonymous %}
                            <i class="d-block d-md-none fas fa-large fa-user" ></i>
                        {% else %}
                            <img class="d-block d-md-none img-rounded" src="{{ url_for('user.view_avatar') }}" id="loginImageMobile">
                        {% endif %}
                    </button>
                </div>
            </div>

            <!-- The actual navigation menu -->
            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav">
                    {% for entry in navigation_bar_entries %}

                        {% if entry.activity_list %}
                        <li class="dropdown navbar-item">
                            <a href="{{ entry.href }}" class="nav-link dropdown-toggle">{{ entry.title }}</a>
                            <ul class="dropdown-menu dropdown-menu-activity">
                                {% for activity in entry.activities %}
                                <div>
                                    <a class="nav-link" href="{{ url_for('activity.get_activity', activity=activity)}}">
                                        <small class="float-right">{{ activity.till_now() }}</small>
                                        {{ activity.name }}
                                        <small class="invisible"> {{ activity.till_now() }}</small>
                                    </a>
                                </div>
                                {% endfor %}
                            </ul>
                        </li>
                        {% else %}
                        <li class="{% if navigation_get_children(entry, current_user) %}dropdown{% endif %} navbar-item">
                            <a class="nav-link{% if entry.children %} dropdown-toggle{% endif %}"
                               {% if entry.external %}target="_blank"{% endif %}
                               href="{{ entry.href }}">
                                {{ entry.title }}
                            </a>

                            <ul class="dropdown-menu">
                                {% for child in navigation_get_children(entry, current_user) %}
                                    <div {% if child.children %}class="dropdown-submenu"{% endif %}>
                                        <a class="nav-link{% if entry.children %} dropdown-toggle {% endif %}" {% if child.external %}target="_blank"{% endif %} href="{{ child.href }}">
                                        {% if child.subtitle is defined%}
                                            <small class="float-right"> {{ child.subtitle|truncate(40)  }}</small>
                                        {% endif %}
                                        {{ child.title }}
                                        {% if child.subtitle is defined %}
                                            <small class="invisible"> {{ child.subtitle|truncate(40)  }}</small>
                                        {% endif %}
                                        </a>
                                        <div class="dropdown-menu">
                                            {% for grand_child in child.children %}
                                                <a class="nav-link d-block" href="{{ grand_child.href }}">{{ grand_child.title }}</a>
                                            {% endfor %}
                                        </div>
                                    </div>
                                {% endfor %}
                            </ul>
                        </li>
                        {% endif %}
                    {% endfor %}
                    <li class="navbar-item">
                        <a class="nav-link" href="{{ url_for("vue.search") }}">
                            <i class="d-none d-md-inline-block fas fa-search mr-2"></i> {{ _('Search') }}
                        </a>
                    </li>
                </ul>
            </div>

            <!-- Dropdowns containers for small menu -->
            <div class="collapse navbar-collapse login-container small" id="navbar-collapse-1">
                {% include 'navigation/language_dropdown.htm' %}
            </div>
            <div class="collapse navbar-collapse login-container small" id="navbar-collapse-2">
                {% include 'navigation/user_dropdown.htm' %}
            </div>

            <!-- Dropdown buttons for large menu -->
            <div class="dropdown float-right">

                <!-- Translation dropdown -->
                <a data-toggle="dropdown" href="#">
                    <i class="d-none d-md-inline-block fas fa-large fa-globe-europe"></i>
                </a>
                <div class="dropdown-menu">
                    {% include 'navigation/language_dropdown.htm' %}
                </div>
            </div>
            <div class="dropdown float-right">

                <!-- User dropdown -->
                {% if current_user.is_anonymous %}
                    <a data-toggle="dropdown" href="#">
                        <i class="d-none d-md-inline-block fas fa-large fa-user"></i>
                    </a>
                {% else %}
                    <a data-toggle="dropdown" href="#">
                        <img class="d-none d-md-block img-rounded login-image" src="{{ url_for('user.view_avatar') }}">
                    </a>
                {% endif %}
                <div class="dropdown-menu dropdown-menu-right login-container">
                    {% include 'navigation/user_dropdown.htm' %}
                </div>
            </div>
        </div>
    </nav>

app/templates/navigation/view_sidebar.htm
{% if navigation_current_entry != None %}

<div class="col-md-2 side-menu">
    <div class="card-group">
        <div class="card">
            {% for i, entry in enumerate(navigation_side_entries) %}
                <a class="card-header" {% if entry.external %}target="_blank"{% endif %} href="{{ entry.href }}">
                    {{ entry.title }}
                </a>
                {% if entry.activity_list %}
                    <ul class="list-group list-group-flush">
                        {% for activity in entry.activities %}
                        <li class="list-group-item">
                            <a href="{{ url_for('activity.get_activity', activity=activity) }}">
                                {{ activity.name }}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    {% if navigation_current_entry.children and entry.id == navigation_current_entry.id %}
                        <ul class="list-group list-group-flush">
                            {% for child in navigation_get_children(navigation_current_entry, current_user) %}
                                <li class="list-group-item">
                                    <a {% if child.external %}target="_blank"{% endif %}
                                       href="{{ child.href }}">
                                        {{ child.title }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

{% endif %}